zn "%SYS"
;; fix sick package mapping in some HSCUSTOM
for p="%IPM","%pkg.isc" do ##Class(Config.MapPackages).Delete("HSCUSTOM",p)

;; Unexpire passwords and set up passwordless mode to simplify dev use.
do ##class(Security.Users).UnExpireUserPasswords("*")
zpm "install passwordless"
zpm "install iterm"

zn "USER"
;; this should be the place for individual application code.
do EnableDeepSee^%SYS.cspServer("/csp/user/")
zpm "list"
write "iris.script completed",!,$ZV,!
halt
